# Generated by Django 4.2.1 on 2023-06-15 03:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.IntegerField(
                        choices=[
                            (1, "とても同意する"),
                            (2, "まあ同意する"),
                            (3, "どちらでもない"),
                            (4, "あまり同意しない"),
                            (5, "全く同意しない"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "genderchoices",
                    models.IntegerField(
                        choices=[(1, "女性"), (2, "男性"), (3, "無回答")], default=3
                    ),
                ),
                (
                    "btypechoice",
                    models.IntegerField(
                        choices=[(1, "A型"), (2, "B型"), (3, "O型"), (4, "AB型")], default=1
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "回答",
                "verbose_name_plural": "回答一覧",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "質問",
                "verbose_name_plural": "質問一覧",
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.question"
            ),
        ),
    ]
