# Generated by Django 4.2.1 on 2023-07-01 12:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '質問',
                'verbose_name_plural': '質問一覧',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('g_choice', models.IntegerField(choices=[(1, '女性'), (2, '男性'), (3, '無回答')], default=3)),
                ('b_choice', models.IntegerField(choices=[(1, 'A型'), (2, 'B型'), (3, 'O型'), (4, 'AB型')], default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'User情報',
                'verbose_name_plural': 'User情報一覧',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(choices=[(1, 'とても同意する'), (2, 'まあ同意する'), (3, 'どちらでもない'), (4, 'あまり同意しない'), (5, '全く同意しない')], default=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='questions.user')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答一覧',
            },
        ),
    ]
