# Generated by Django 4.2.1 on 2023-07-05 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "質問",
                "verbose_name_plural": "質問一覧",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                (
                    "g_choice",
                    models.IntegerField(
                        choices=[(1, "女性"), (2, "男性"), (3, "無回答")], default=3
                    ),
                ),
                (
                    "b_choice",
                    models.IntegerField(
                        choices=[(1, "A型"), (2, "B型"), (3, "O型"), (4, "AB型")], default=1
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "User情報",
                "verbose_name_plural": "User情報一覧",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.IntegerField(
                        choices=[
                            (5, "とても同意する"),
                            (4, "まあ同意する"),
                            (3, "どちらでもない"),
                            (2, "あまり同意しない"),
                            (1, "全く同意しない"),
                        ],
                        default=3,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "回答",
                "verbose_name_plural": "回答一覧",
            },
        ),
    ]
