# Generated by Django 4.2.1 on 2023-06-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_answer_btypechoice_answer_genderchoices_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="btypechoice",
            field=models.IntegerField(
                choices=[(1, "A型"), (2, "B型"), (3, "O型"), (4, "AB型")], default=1
            ),
        ),
    ]
