# Generated by Django 4.2.1 on 2023-06-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_rename_questions_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item1",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item2",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item3",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item4",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item5",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item6",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item7",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item8",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item9",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item10",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item11",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item12",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item13",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item14",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item15",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item16",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item17",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
                (
                    "item18",
                    models.IntegerField(
                        choices=[
                            (1, "全く同意しない"),
                            (2, "あまり同意しない"),
                            (3, "どちらでもない"),
                            (4, "まあ同意する"),
                            (5, "とても同意する"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="bloodtype",
            field=models.CharField(
                choices=[("A", "A型"), ("B", "B型"), ("O", "O型"), ("AB", "AB型")],
                default="",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("N", "Noanswer")],
                default="",
                max_length=1,
            ),
        ),
    ]
